CREATE TABLE PAT_CHKUP( PAT_NO VARCHAR(8), DOC_NO VARCHAR(8), DIAGNOSIS VARCHAR(50),
STATUS VARCHAR(10), TREATMENT VARCHAR(35),
CONSTRAINT PRCKRFKY foreign key (PAT_NO) REFERENCES PAT_ENTRY(PAT_NO),
CONSTRAINT PTRFDCPRKY foreign key (DOC_NO) REFERENCES ALL_DOCTORS(DOC_NO)
);
