CREATE TABLE ALL_DOCTORS ( DOC_NO VARCHAR(8) unique primary key constraint LIKETHESE CHECK (
DOC_NO LIKE 'DR%' OR DOC_NO LIKE 'DC%'),
DEPARTMENT varchar(20),
CONSTRAINT ADDFRKYDMT FOREIGN KEY (DEPARTMENT)
REFERENCES DEPARTMENT(D_NAME)
);
